# Generated by Django 5.0.6 on 2024-06-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Authors',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Authors.authors'),
        ),
    ]
